### ISSUE TITLE
Using Multiple together with Counter and Lookbehind loses information from Lookbehind

### ISSUE THREAD

**Issue by daFish** [hoaproject/Iterator#28]
I'm trying to use the `Multiple`-iterator together with `Counter` and `Lookbehind`:

```php
$iterator = new \IteratorIterator(new \ArrayIterator($array));
$lookBehind = new Lookbehind($iterator);
$counter = new Counter(0, count($array), 1);
$multiple = new Multiple(Multiple::MIT_NEED_ALL|Multiple::MIT_KEYS_NUMERIC);
$multiple->attachIterator($lookBehind, 'lb');
$multiple->attachIterator($counter, 'c');

foreach ($multiple as $iterator) {
    $iterator['lb']->hasPrevious(); // Call to a member function getPrevious()
}
```

I was expecting that I could use both attached iterators with all their features but `$iterator['lb']` will only hold the contents of `$array` for the given iteration.

**Comment by Hywan** [comment]
Hello :smiley:,

First, you are using `Iterator\Multiple::MIT_KEYS_NUMERIC`, which implies using `0` and `1` to access iterators instead of `lb` and `c`. Using `Iterator\Multiple::MIT_KEYS_ASSOC` will solve this issue.

Second, each value returned by the multiple iterator is an array whose values are not the iterators themselves but their respective produced values. So the `hasPrevious` method does not exist since `$iterator['lb']` is not an object. You might would like to use it like this:

```php
use Hoa\Iterator;

$counter    = new Iterator\Counter(0, 5, 1);
$lookbehind = new Iterator\Lookbehind(
    new Iterator\Map(range('a', 'e'))
);

$multiple = new Iterator\Multiple(
    Iterator\Multiple::MIT_NEED_ANY
  | Iterator\Multiple::MIT_KEYS_ASSOC
);
$multiple->attachIterator($counter, 'counter');
$multiple->attachIterator($lookbehind, 'lookbehind');

foreach ($multiple as $iterators) {
    echo
        '[counter] current: ', $iterators['counter'], "\n",
        '[lookbehind] current: ', $iterators['lookbehind'], "\n";

    if (true === $lookbehind->hasPrevious()) {
        echo '[lookbehind] previous: ', $lookbehind->getPrevious(), "\n";
    }

    echo "\n";
}
```

The output of this program is:
```
[counter] current: 0
[lookbehind] current: a

[counter] current: 1
[lookbehind] current: b
[lookbehind] previous: a

[counter] current: 2
[lookbehind] current: c
[lookbehind] previous: b

[counter] current: 3
[lookbehind] current: d
[lookbehind] previous: c

[counter] current: 4
[lookbehind] current: e
[lookbehind] previous: d

```

which looks like what is desired. The key part is to use the `$lookbehind` iterator inside the loop. This is object passed by reference and its internal iterator pointer is moved by the `$multiple` iterator.

Is it OK?

**Comment by Hywan** [comment]
Calling `$iterators['counter']` from inside the loop is strictly equivalent to call `$counter->current()`. The original iterator is not always accessible from this scope, which can be annoying with the lookbehind iterator for instance.

**Comment by daFish** [comment]
@Hywan Thanks for the detailed explanation. I've tried your solution and it works as expected.
